openapi: 3.0.0
info:
  version: 1.0.0
  title: tukusi server API
  description: >-
    つくしちゃんはかわいいAPI
servers:
  - url: 'http://localhost:3000'
security:
  - BearerAuth: [ ]
paths:
  /api/metas:
    get:
      description: get meta infomation like CSRF token.
      responses:
        200:
          description: meta infomation like CSRF token.
          content:
            application/json:
              schema:
                $ref: './components/schemas/Meta.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
