openapi: 3.0.0
info:
  version: 1.0.0
  title: tukusi server API
  description: >-
    つくしちゃんはかわいいAPI
servers:
  - url: 'http://localhost:3000'
security:
  - BearerAuth: [ ]
paths: { }
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
