name: RSpec
on: push

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6.1
        env:
          MYSQL_DATABASE: tukusi
          MYSQL_ROOT_PASSWORD: tukusi
          MYSQL_USER: tuksui
          MYSQL_PASSWORD: tukusi
        ports:
          - 3306:3306
      redis:
        image: redis:6.2.4
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Run tests
        env:
          DB_DATABASE: tukusi
          DB_USERNAME: root
          DB_PASSWORD: tukusi
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:migrate
          bundle exec rspec
